The_NewYork_Time/The_NewYork_Time/Areas/Admin/Controllers/ArticlesAdminController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using The_NewYork_Time.Models;

namespace The_NewYork_Time.Areas.Admin.Controllers
{
    public class ArticlesAdminController : Controller
    {
        private TNYTContext db = new TNYTContext();
        [Authorize(Roles = "Admin")]
        // GET: Admin/ArticlesAdmin
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "Id" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date_desc" : "Date";
            ViewBag.TenSortParm = sortOrder == "Ten" ? "Ten_desc" : "Ten";

            //phan trang
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            //tìm kiếm
            var articles = from s in db.Articles
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                articles = articles.Where(s => s.articlename.Contains(searchString));
                //|| s.author.Contains(searchString)
                //|| s.description.Contains(searchString)
                //|| s.content1.Contains(searchString));
            }
            //sắp xếp 
            switch (sortOrder)
            {
                case "Id":
                    articles = articles.OrderByDescending(s => s.Id);
                    break;
                case "Date":
                    articles = articles.OrderBy(s => s.date);
                    break;
                case "Date_desc":
                    articles = articles.OrderByDescending(s => s.date);
                    break;
                case "Ten":
                    articles = articles.OrderBy(s => s.articlename);
                    break;
                case "Ten_desc":
                    articles = articles.OrderByDescending(s => s.articlename);
                    break;
                default:
                    articles = articles.OrderBy(s => s.Id);
                    break;
            }
            //var articles = db.Articles.Include(a => a.Cetegory);
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(articles.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/ArticlesAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Admin/ArticlesAdmin/Create
        public ActionResult Create()
        {
            ViewBag.idcategory = new SelectList(db.Categories, "Id", "categoryname");
            return View();
        }

        // POST: Admin/ArticlesAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Id,articlename,description,image,contentarticle,author,date,idcategory")] Article article)
        {
            if (ModelState.IsValid)
            {
                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idcategory = new SelectList(db.Categories, "Id", "categoryname", article.idcategory);
            return View(article);
        }

        // GET: Admin/ArticlesAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            ViewBag.idcategory = new SelectList(db.Categories, "Id", "categoryname", article.idcategory);
            return View(article);
        }

        // POST: Admin/ArticlesAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,articlename,description,image,contentarticle,author,date,idcategory")] Article article)
        {
            if (ModelState.IsValid)
            {
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idcategory = new SelectList(db.Categories, "Id", "categoryname", article.idcategory);
            return View(article);
        }

        // GET: Admin/ArticlesAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Admin/ArticlesAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateInput(false)]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/ArticlesAdmin/Create.cshtml
@model The_NewYork_Time.Models.Article

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}
<script src="~/Areas/AssetAdmin/ckeditor/ckeditor.js"></script>


@using (Html.BeginForm("Create", "ArticlesAdmin", FormMethod.Post, new { @class = "form" }))
{


    <div class="form-horizontal">
        <h2 class="admin-title">Create Article</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.articlename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.articlename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articlename, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contentarticle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea class="ckeditor" name="contentarticle" [ValidateInput(false)]></textarea>
                @*@Html.TextAreaFor(model => model.content1, htmlAttributes: new { id = "content", @class = "control-label" })
                    @Html.ValidationMessageFor(model => model.content1, "", new { @class = "text-danger" })*@
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idcategory, "idcategory", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idcategory", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idcategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-10">
            <div class="col-md-offset-2 btn-touch">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
        <div class="col-md-10 back-to-list">
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/ArticlesAdmin/Delete.cshtml
@model The_NewYork_Time.Models.Article

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}

<div class="max">
    <h2 class="admin-title">Delete Article</h2>
    <hr />
    <h3 class="question">Are you sure you want to delete this article?</h3>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.categoryname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.categoryname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.articlename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.articlename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contentarticle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contentarticle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions btn-touch">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
        <div class=" col-md-12 back-to-list">
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/ArticlesAdmin/Details.cshtml
@model The_NewYork_Time.Models.Article

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}



<div class="form">
    <h2 class="admin-title">Details Article</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.categoryname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.categoryname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.articlename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.articlename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.image)" width="50%"alt="Alternate Text" />     
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contentarticle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contentarticle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>
    <div class=" col-md-12 back-to-list">
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
    </div>
    <div class=" col-md-12 back-to-list">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/ArticlesAdmin/Edit.cshtml
@model The_NewYork_Time.Models.Article

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}
<script src="~/Areas/AssetAdmin/ckeditor/ckeditor.js"></script>


@using (Html.BeginForm("Edit", "ArticlesAdmin", FormMethod.Post, new { @class = "form" }))
{


<div class="form-horizontal">
    <h2 class="admin-title">Edit Article</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.articlename, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.articlename, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.articlename, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.contentarticle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <textarea class="ckeditor" name="contentarticle" [ValidateInput(false)]></textarea>
            @*@Html.TextAreaFor(model => model.content1, htmlAttributes: new { id = "content", @class = "control-label" })
                @Html.ValidationMessageFor(model => model.content1, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.author, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.author, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.author, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.idcategory, "idcategory", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idcategory", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idcategory, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-md-10">
        <div class="col-md-offset-2 btn-touch">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
    <div class="col-md-10 back-to-list">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
}

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/ArticlesAdmin/Index.cshtml
@model PagedList.IPagedList<The_NewYork_Time.Models.Article>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <form class="form-inline">
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
            </form>

            <!-- Topbar Search -->
            <form method="post" action="/Admin/ArticlesAdmin" class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input class="col-md-10" type="text" name="SearchString" class="form-control bg-light border-0 small" placeholder="Search for @ViewBag.CurrentFilter"
                           aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append col-md-2">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-search fa-fw"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                         aria-labelledby="searchDropdown">
                        <form class="form-inline mr-auto w-100 navbar-search">
                            <div class="input-group">
                                <input type="text" class="form-control bg-light border-0 small"
                                       placeholder="Search for..." aria-label="Search"
                                       aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="button">
                                        <i class="fas fa-search fa-sm"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>



                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small"></span>
                        <img class="img-profile rounded-circle"
                             src="img/undraw_profile.svg">
                    </a>
                    <!-- Dropdown - User Information -->

                </li>

            </ul>

        </nav>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- Page Heading -->
            <h1 class="h3 mb-2 text-gray-800">Article</h1>
            <p>
                @Html.ActionLink("Create New", "Create")
            </p>



            <!-- DataTales Example -->
            <div class="card shadow mb-4">

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                            <thead>
                                <tr>
                                    <th>
                                        @Html.ActionLink("ID", "Index", new { sortOrder = ViewBag.IdSortParm, currentFilter = ViewBag.CurrentFilter })
                                    </th>

                                    <th>
                                        CategoryName
                                    </th>
                                    <th>
                                        @Html.ActionLink(" Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
                                    </th>
                                    <th>
                                        @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.TenSortParm, currentFilter = ViewBag.CurrentFilter })
                                    </th>
                                    <th>
                                        Description
                                    </th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Author
                                    </th>
                                    <th width="170px"> Option</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Category.categoryname)
                                        </td>
                                        <td>
                                            @item.date.ToString("dd/MM/yyyy")
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.articlename)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.description)
                                        </td>
                                        <td>
                                            <img src="@Html.DisplayFor(modelItem => item.image)" width="200px" height="auto" alt="Alternate Text" />
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.author)
                                        </td>

                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                }




                            </tbody>
                        </table>
                        <br />
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                        @Html.PagedListPager(Model, page => Url.Action("Index",
                            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->
    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright &copy; Your Website 2020</span>
            </div>
        </div>
    </footer>
    <!-- End of Footer -->

</div>