The_NewYork_Time/The_NewYork_Time/Areas/Admin/Controllers/SectionsAdminController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using The_NewYork_Time.Models;

namespace The_NewYork_Time.Areas.Admin.Controllers
{
    public class SectionsAdminController : Controller
    {
        private TNYTContext db = new TNYTContext();
        [Authorize(Roles = "Admin")]
        // GET: Admin/SectionsAdmin
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "Id" : "";
            ViewBag.TenSortParm = sortOrder == "Ten" ? "Ten_desc" : "Ten";

            //phan trang
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            //tìm kiếm
            var sections = from s in db.Sections
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                sections = sections.Where(s => s.sectionname.Contains(searchString));
                //|| s.author.Contains(searchString)
                //|| s.description.Contains(searchString)
                //|| s.content1.Contains(searchString));
            }
            //sắp xếp 
            switch (sortOrder)
            {
                case "Id":
                    sections = sections.OrderByDescending(s => s.Id);
                    break;
                case "Ten":
                    sections = sections.OrderBy(s => s.sectionname);
                    break;
                case "Ten_desc":
                    sections = sections.OrderByDescending(s => s.sectionname);
                    break;
                default:
                    sections = sections.OrderBy(s => s.Id);
                    break;
            }
            //var articles = db.Articles.Include(a => a.Cetegory);
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(sections.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/SectionsAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // GET: Admin/SectionsAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/SectionsAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,sectionname")] Section section)
        {
            if (ModelState.IsValid)
            {
                db.Sections.Add(section);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(section);
        }

        // GET: Admin/SectionsAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: Admin/SectionsAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,sectionname")] Section section)
        {
            if (ModelState.IsValid)
            {
                db.Entry(section).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(section);
        }

        // GET: Admin/SectionsAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: Admin/SectionsAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Section section = db.Sections.Find(id);
            db.Sections.Remove(section);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/SectionsAdmin/Create.cshtml
@model The_NewYork_Time.Models.Section

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}



@using (Html.BeginForm("Create", "SectionsAdmin", FormMethod.Post, new { @class = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2 class="admin-title">Create Section</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.sectionname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sectionname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sectionname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-md-10">
        <div class="col-md-offset-2 btn-touch">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
    <div class="col-md-10 back-to-list" >
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
}

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/SectionsAdmin/Delete.cshtml
@model The_NewYork_Time.Models.Section

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}

<div class="max">
    <h2 class="admin-title">Delete Section</h2>
    <hr />
    <h3 class="question">Are you sure you want to delete this section?</h3>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sectionname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sectionname)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions btn-touch">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
        <div class=" col-md-12 back-to-list">
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/SectionsAdmin/Details.cshtml
@model The_NewYork_Time.Models.Section

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}



<div class="form">
    <h2 class="admin-title">Details Section</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sectionname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sectionname)
        </dd>

    </dl>
    <div class=" col-md-12 back-to-list">
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
    </div>
    <div class=" col-md-12 back-to-list">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/SectionsAdmin/Edit.cshtml
@model The_NewYork_Time.Models.Section

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}



@using (Html.BeginForm("Edit", "SectionsAdmin", FormMethod.Post, new { @class = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2 class="admin-title">Edit Section</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.sectionname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sectionname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sectionname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-md-10">
        <div class="col-md-offset-2 btn-touch">
            <input type="submit" value="Save" class="btn btn-warning" />
        </div>
    </div>
    <div class="col-md-10 back-to-list">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
}

The_NewYork_Time/The_NewYork_Time/Areas/Admin/Views/SectionsAdmin/Index.cshtml
@model PagedList.IPagedList<The_NewYork_Time.Models.Section>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Main_Layout.cshtml";
}



<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <form class="form-inline">
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
            </form>

            <!-- Topbar Search -->
            <form method="post" action="/Admin/SectionsAdmin" class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input class="col-md-10" type="text" name="SearchString" class="form-control bg-light border-0 small" placeholder="Search for @ViewBag.CurrentFilter"
                           aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append col-md-2">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-search fa-fw"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                         aria-labelledby="searchDropdown">
                        <form class="form-inline mr-auto w-100 navbar-search">
                            <div class="input-group">
                                <input type="text" class="form-control bg-light border-0 small"
                                       placeholder="Search for..." aria-label="Search"
                                       aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="button">
                                        <i class="fas fa-search fa-sm"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>



                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small"></span>
                        <img class="img-profile rounded-circle"
                             src="img/undraw_profile.svg">
                    </a>
                    <!-- Dropdown - User Information -->

                </li>

            </ul>

        </nav>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- Page Heading -->
            <h1 class="h3 mb-2 text-gray-800">Section</h1>
            <p>
                @Html.ActionLink("Create New", "Create")
            </p>

            <!-- DataTales Example -->
            <div class="card shadow mb-4">

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                            <thead>
                                <tr>
                                    <th>
                                        @Html.ActionLink("ID", "Index", new { sortOrder = ViewBag.IdSortParm, currentFilter = ViewBag.CurrentFilter })
                                    </th>
                                    <th>
                                        @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.TenSortParm, currentFilter = ViewBag.CurrentFilter })
                                    </th>
                                    <th> Option</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.sectionname)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>

                                }



                            </tbody>
                        </table>
                        <br />
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                        @Html.PagedListPager(Model, page => Url.Action("Index",
                            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->
    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright &copy; Your Website 2020</span>
            </div>
        </div>
    </footer>
    <!-- End of Footer -->

</div>