The_NewYork_Time/The_NewYork_Time/Controllers/SearchController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using The_NewYork_Time.Models;

namespace The_NewYork_Time.Controllers
{
    public class SearchController : Controller
    {
        private TNYTContext db = new TNYTContext();
        // GET: Search
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            
            ViewBag.CurrentSort = sortOrder;
            

            //phan trang
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            //tìm kiếm
            var articles = from s in db.Articles
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                articles = articles.Where(s => s.articlename.Contains(searchString));
                //|| s.author.Contains(searchString)
                //|| s.description.Contains(searchString)
                //|| s.content1.Contains(searchString));
            }
            //sắp xếp 
            switch (sortOrder)
            {
               
                default:
                    articles = articles.OrderBy(s => s.Id);
                    break;
            }
            //var articles = db.Articles.Include(a => a.Cetegory);
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(articles.ToPagedList(pageNumber, pageSize));
        }
    }
}

The_NewYork_Time/The_NewYork_Time/Controllers/SectionsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using The_NewYork_Time.Models;

namespace The_NewYork_Time.Views
{
    public class SectionsController : Controller
    {
        private TNYTContext db = new TNYTContext();

        // GET: Sections
        
        public ActionResult Category(int id, int page = 1, int pagesize = 5)
        {
            //var ds = The_NewYork_Time.Models.BUS.ArticleBUS.DanhSachArticleTheoCate(id).ToPagedList(page, pagesize);
            IQueryable<Article> listArticle = null;

            listArticle = from a in db.Articles
                          where a.idcategory == id
                          orderby a.Id
                          select a;
            var showlist = listArticle.ToPagedList(page, pagesize);
            return View(showlist);
        }
    }

}

The_NewYork_Time/The_NewYork_Time/Views/Search/Index.cshtml
@model PagedList.IPagedList<The_NewYork_Time.Models.Article>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Result";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var currentFilter = ViewBag.CurrentFilter;
}


<!-- End Section Header -->
<section id="latest">
    <div>
        <!-- Tab items -->
        <div class="tabs">
            <div class="tab-item active">
                Show All Result Of @currentFilter
            </div>
           
           

            <div class="line"></div>
        </div>

        <!-- Tab content -->
        <div class="tab-content ">
            <div class="tab-pane active">
                @foreach (var item in Model)
                {
                    <div class="lastes-item rowp">
                        <div class="lastes-item-content">
                            <div class="col col-2 display-sm">
                                <span>@item.date.ToString("dd/MM/yyyy")</span>
                            </div>
                            <div class="col col-7 col-sm12">
                                <h2>
                                    <a href="/Categories/Article/@item.Id">
                                        @item.articlename
                                    </a>
                                </h2>
                                <p>@item.description</p>
                                <p class="article-author">
                                    By @item.author
                                </p>
                            </div>
                            <div class="col col-3 col-sm12">
                                <a href="/Categories/Article/@item.Id">
                                    <img src="@item.image" alt="">
                                </a>
                            </div>
                        </div>


                    </div>
                }

                <!-- Pagination Start -->
                <div class="col-md-12 page">
                    <div class="pagination justify-content-center">
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                        @Html.PagedListPager(Model, Page => Url.Action("Index", "Search", new { Page }))
                    </div>
                </div>
                <!-- Pagination Start -->
            </div>
            


        </div>
    </div>
</section>
<script>
    tab()
</script>
<!-- End Section Latest -->

The_NewYork_Time/The_NewYork_Time/Views/Search/Search.cshtml
@model PagedList.IPagedList<The_NewYork_Time.Models.Article>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Search</h2>

<div id="div1">
    <div id="div2">
        <p>Showing 29.212 results for:</p>
        <h3> Covid </h3>
        <select style="margin-left: -109px;">
            <option value="">Sort by Relevance</option>
            <option value="">Sort by Newest</option>
            <option value="">Sort by Oldest</option>
        </select>

        <select>
            <option value="">Section</option>
            <option value="">U.S</option>
            <option value="">World</option>
        </select>

    </div>
    <form action="" class="search">
        <label for="birthday">Date Range:</label>
        <input type="date" id="Date Range" name="Date Range">
        <button type="submit"> Go</button>
    </form>
</div>
@foreach (var item in Model)
{
    <div class="lastes-item rowp">
        <div class="col col-2">
            <span>@item.date.ToString("dd/MM/yyyy")</span>
        </div>
        <div class="col col-7">
            <a class="caterogy" href="#">Health</a>
            <h2>
                <a href="#">
                    @item.articlename
                </a>
            </h2>
            <p>@item.description.</p>
            <a id="author" href="#">By @item.author</a>
            <br>
            <p id="print">Print Edition: </p>
            <a href="">May 25,1968</a> | <a href="">Johnathan</a>
        </div>
        <div class="col col-3">
            <img src="@item.image1" alt="">
        </div>
    </div>
    <!-- Pagination Start -->
    <div class="col-md-12 page">
        <div class="pagination justify-content-center">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            @Html.PagedListPager(Model, Page => Url.Action("Category", "Sections", new { Page }))
        </div>
    </div>
    <!-- Pagination Start -->
}