The_NewYork_Time/The_NewYork_Time/Models/Category.cs
namespace The_NewYork_Time.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Category")]
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            Articles = new HashSet<Article>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string categoryname { get; set; }

        public int idsection { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }

        public virtual Section Section { get; set; }
    }
}

The_NewYork_Time/The_NewYork_Time/Controllers/CategoriesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using The_NewYork_Time.Models;

namespace The_NewYork_Time.Controllers
{
    public class CategoriesController : Controller
    {
        private TNYTContext db = new TNYTContext();

        public ActionResult Article(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Article article = db.Articles.Find(id);
            var objArticle = db.Articles.Where(p => p.Id == id);

            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            var userID = User.Identity.GetUserId();
            foreach (Article item in objArticle)
            {
                //lấy danh sanh tham gia khóa học
                if (userID != null)
                {
                    item.isLogin = true;
                    //Kiểm tra user đó chưa tham gia khóa học
                    Storage find = db.Storages.FirstOrDefault(p => p.ArticleId == item.Id && p.UserId == userID);
                    if (find == null)
                        item.isShowSave = true;
                }
            }
            
            return View(article);
        }
    }
}

The_NewYork_Time/The_NewYork_Time/Controllers/SectionsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using The_NewYork_Time.Models;

namespace The_NewYork_Time.Views
{
    public class SectionsController : Controller
    {
        private TNYTContext db = new TNYTContext();

        // GET: Sections
        
        public ActionResult Category(int id, int page = 1, int pagesize = 5)
        {
            //var ds = The_NewYork_Time.Models.BUS.ArticleBUS.DanhSachArticleTheoCate(id).ToPagedList(page, pagesize);
            IQueryable<Article> listArticle = null;

            listArticle = from a in db.Articles
                          where a.idcategory == id
                          orderby a.Id
                          select a;
            var showlist = listArticle.ToPagedList(page, pagesize);
            return View(showlist);
        }
    }

}

The_NewYork_Time/The_NewYork_Time/Views/Shared/_2ndArticleSection.cshtml
@model IEnumerable<The_NewYork_Time.Models.Article>

<div class="col col-3 col-md5 col-sm12 content-center">
    @foreach(var item in Model)
 {
    <div class="">
        <div class="head-img">
            <a href="/Categories/Article/@item.Id">
                <img src="@item.image" alt="">
            </a>

            <p>@item.author FOR THE NEW YORK TIMES</p>
        </div>
        <div class="head-content">
            <div class="head-title">
                <h2><a href="/Categories/Article/@item.Id">@item.articlename</a></h2>
            </div>
            <div class="head-descrip">
                <p>@item.description</p>
            </div>
            <div class="head-article">
                <span class="minute">
                    15h ago
                </span>
                <span class="space"></span>
                <span class="name-aricle">
                    By @item.author
                </span>
            </div>
        </div>
    </div>
    }
    
</div>

The_NewYork_Time/The_NewYork_Time/Views/Shared/_2ndNewArticleHome.cshtml
@model IEnumerable<The_NewYork_Time.Models.Article>
@foreach (var item in Model)
{
    <div class="col-8">
        <div class="row">
            <div class="col-md-4">
                <div class="paper">
                    <div class="paper-body ">
                        <h5 class="title-paper "><a class="text-decoration-none text-dark" href="@Url.Action("Article","Categories" ,new { id =item.Id})">@item.articlename</a></h5>
                        <ul class="paper-list-abstract" style="list-style:none;">
                            <li class="paper-item-abstract text-decoration-none text-black-50">@item.description</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <a href="@Url.Action("Article","Categories" ,new { id =item.Id})"><img class="carg-img" style=" width: 100%;" src="@item.image" alt="@Url.Action("Article","Categories" ,new { id =item.Id})"></a>
                <p class="caption-picture text-decoration-none text-dark">Allen Weisselberg, center, arriving in court to face charges of receiving fringe benefits without paying taxes on them. Jefferson Siegel for The New York Times</p>
            </div>
        </div>
    </div>
}

The_NewYork_Time/The_NewYork_Time/Views/Shared/_3rdArticleSection.cshtml
@model IEnumerable<The_NewYork_Time.Models.Article>
<div class="col col-md6 head-content content-right">
    @foreach (var item in Model)
    {
        <div class="head-title">
            <h2><a href="/Categories/Article/@item.Id">@item.articlename</a></h2>
        </div>
        <div class="head-img-right">
            <a href="/Categories/Article/@item.Id">
                <img src="@item.image" alt="">
            </a>


        </div>
        <div class="head-descrip">
            <p>@item.description</p>
        </div>
        <div class="head-article">
            <span class="minute">
                10h ago

            </span>
            <span class="space"></span>
            <span class="name-aricle">
                By @item.author
            </span>
        </div>
    }
    </div>

The_NewYork_Time/The_NewYork_Time/Views/Shared/_4thArticleSection.cshtml
@model IEnumerable<The_NewYork_Time.Models.Article>
<div class="col col-md6 head-content mt-19 mt-bd-0">
    @foreach (var item in Model)
    {
        <div class="head-title">
            <h2><a href="/Categories/Article/@item.Id">@item.articlename</a></h2>
        </div>
        <div class="head-img-right">
            <a href="/Categories/Article/@item.Id">
                <img src="@item.image" alt="">
            </a>


        </div>
        <div class="head-descrip">
            <p>@item.description</p>
        </div>
        <div class="head-article">
            <span class="minute">
                13h ago
            </span>
            <span class="space"></span>
            <span class="name-aricle">
                By @item.author
            </span>
        </div>
    }
    </div>

The_NewYork_Time/The_NewYork_Time/Views/Shared/_ArticleLastestBySection.cshtml
@model IEnumerable<The_NewYork_Time.Models.Article>

<!-- Section Latest -->
<section id="latest">
    <div>
        <!-- Tab items -->
        <div class="tabs">
            <div class="tab-item active">

                Latest
            </div>
            @*<div class="tab-item">
                <form action="">
                    <input placeholder="Search" style="padding: 2px 0; border-radius: 5px;">
                    <i class="ti-search"></i>
                </form>

            </div>*@

            <div class="line"></div>
        </div>

        <!-- Tab content -->
        <div class="tab-content ">
            <div class="tab-pane active">
                @foreach(var item in Model) { 
                <div class="lastes-item rowp">
                    <div class="col col-2  display-sm">
                        <span>@item.date.ToString("dd/MM/yyyy")</span>
                    </div>
                    <div class="col col-7 col-sm12">
                        <h2>
                            <a href="/Categories/Article/@item.Id">
                               @item.articlename
                            </a>
                        </h2>
                        <p>@item.description</p>
                    </div>
                    <div class="col col-3 col-sm12">
                        <a href="/Categories/Article/@item.Id">
                            <img src="@item.image" alt="">

                        </a>
                    </div>
                </div>
                }
            </div>
            @*<div class="tab-pane">
                <div class="lastes-item rowp">
                    <div class="col col-2 display-sm">
                        <span>June 24, 2021</span>
                    </div>
                    <div class="col col-7 col-sm12">
                        <h2>
                            <a href="#">
                                Brazil Passes 500,000 Covid Deaths, a Tragedy With No Sign of Letup
                            </a>
                        </h2>
                        <p>With 2.7 percent of the world’s population, Brazil has suffered 13 percent of the Covid-19 fatalities, and the pandemic there is not abating.</p>
                    </div>
                    <div class="col col-3 col-sm12 mt-19">
                        <img src="https://static01.nyt.com/images/2021/06/21/world/00Brazil-Covid-Deaths-Photos-Top-promo/00Brazil-Covid-Deaths-Photos-Top-mediumThreeByTwo252.jpg?quality=100&auto=webp" alt="">
                    </div>
                </div>
                <div class="lastes-item rowp">
                    <div class="col col-2 display-sm">
                        <span>June 24, 2021</span>
                    </div>
                    <div class="col col-7 col-sm12">
                        <h2>
                            <a href="#">
                                Why More People Are Getting Two Different Coronavirus Vaccines
                            </a>
                        </h2>
                        <p>
                            Several countries are allowing mix-and-match inoculation, which scientists hope will have benefits, and Chancellor Angela Merkel of Germany is among those to get it.

                        </p>
                    </div>
                    <div class="col col-3 col-sm12 mt-19">
                        <img src="https://static01.nyt.com/images/2021/06/23/world/23mix-n-match-explainer01/merlin_187969563_eed9bb59-2ad2-4862-bb44-ebbd4ca946a5-mediumThreeByTwo252.jpg?quality=100&auto=webp" alt="">
                    </div>
                </div>

            </div>*@
        </div>
    </div>
</section>
<!-- End Section Latest -->

The_NewYork_Time/The_NewYork_Time/Views/Shared/_ArticlesOfCateInSection.cshtml
@model IEnumerable<The_NewYork_Time.Models.Article>
<ul class="list-content">
    @foreach (var item in Model)
    {
        <li>
            
            <a href="/Categories/Article/@item.Id">
                <img src="@item.image" alt="">
            </a>
            <h2>
                <a href="/Categories/Article/@item.Id">@item.description</a>
            </h2>
        </li>
    }

   

</ul>

The_NewYork_Time/The_NewYork_Time/Views/Shared/_CateOfFooterPage.cshtml
@model IEnumerable<The_NewYork_Time.Models.Category>
<ul class="footer-category__list">
    @foreach (var item in Model)
    {
    <li class="footer-category__item"><a href="@Url.Action("Category","Sections",new {id =item.Id })" class="footer-category__link">@item.categoryname</a></li>
    }


</ul>

The_NewYork_Time/The_NewYork_Time/Views/Shared/_CategoryHeader.cshtml
@model The_NewYork_Time.Models.Category

<header id="section-header" class="page">
    <div class="section-world">
        <a href="/Home/Section/@Model.Id" class="section-header-link">
            <p>@Model.Section.sectionname</p>
        </a>
    </div>
    <div class="section-title">
        <h1>@Model.categoryname</h1>
    </div>
</header>

The_NewYork_Time/The_NewYork_Time/Views/Shared/_Random_10_Article.cshtml
@model IEnumerable<The_NewYork_Time.Models.Article>


<div class="section-content-center">
    <ul class="list-content">
        @foreach (var item in Model)
        {
            <li>
                <a href="/Categories/Article/@item.Id">
                    <img  src="@item.image" alt="">
                </a>
                <h2 style="word-break: break-word; padding-top: 20px;">
                    <a href="/Categories/Article/@item.Id">@item.articlename</a>
                </h2>

            </li>
        }
        </ul>
</div>

The_NewYork_Time/The_NewYork_Time/Views/Shared/_SectionChan.cshtml
@model IEnumerable<The_NewYork_Time.Models.Section>

@foreach (var item in Model)
{
    @Html.Partial("_ArticleChan", The_NewYork_Time.Models.BUS.ArticleBUS.ShowArticleSectionchan(item.Id))
}

The_NewYork_Time/The_NewYork_Time/Views/Shared/_ShowArticleofCatetoSection.cshtml
@model IEnumerable<The_NewYork_Time.Models.Category>

@foreach(var item in Model)
{ 
<!-- Section US -->
<section id="us">
    <div class="nation-header">
        <h2>
            <a href="/Sections/Category/@item.Id">@item.categoryname</a>
        </h2>
        <a href="/Sections/Category/@item.Id">More in Read The @item.categoryname ></a>
    </div>
    <div class="us-content">
        @Html.Partial("_ArticlesOfCateInSection", The_NewYork_Time.Models.BUS.ArticleBUS.ShowArticleToCate(item.Id))
    </div>

</section>
<!-- End Section Us -->
}

The_NewYork_Time/The_NewYork_Time/Views/Shared/_showcatename.cshtml
@model IEnumerable<The_NewYork_Time.Models.Category>


    @foreach (var item in Model)
    {
       
        <ul class="menu-sub__list">

            <li class="menu-sub__item"><a href="@Url.Action("Category","Sections",new {id =item.Id })" class="menu-item__link">@item.categoryname</a></li>

        </ul>
    }